# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
# windmill.nodepool
nodepool_user_shell: /bin/bash

nodepool_file_builder_logging_conf_manage: false
nodepool_file_launcher_logging_conf_manage: false

nodepool_file_nodepool_builder_service_config_manage: false
nodepool_file_nodepool_builder_service_manage: false

nodepool_file_nodepool_launcher_service_config_manage: false
nodepool_file_nodepool_launcher_service_manage: false

nodepool_file_nodepool_yaml_src: "{{ windmill_config_git_dest }}/nodepool/nodepool.yaml"
nodepool_file_secure_conf_src: "{{ windmill_config_git_dest }}/nodepool/secure.conf.j2"

nodepool_service_nodepool_builder_enabled: false
nodepool_service_nodepool_builder_manage: false
nodepool_service_nodepool_builder_state: stopped

nodepool_service_nodepool_launcher_enabled: false
nodepool_service_nodepool_launcher_manage: false
nodepool_service_nodepool_launcher_state: stopped

nodepool_pip_version: 3.5.0
nodepool_pip_virtualenv_python: python3
nodepool_pip_virtualenv: "/opt/venv/nodepool-{{ nodepool_pip_version }}"

# windmill.openstacksdk
openstacksdk_user_name: nodepool
openstacksdk_user_group: nodepool
openstacksdk_user_home: /var/lib/nodepool

openstacksdk_pip_virtualenv_python: python3
openstacksdk_pip_virtualenv: "{{ nodepool_pip_virtualenv }}"

openstacksdk_file_clouds_yaml_src: "{{ windmill_config_git_dest }}/nodepool/clouds.yaml.j2"

# clouds.yaml
__nodepool_clouds_yaml_limestone_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36393737616662373736343639336364313137323337383664666432656161653439363161313766
  6139323831366432616165653863383461333336366231370a393464383364663537303430363438
  66346232346666353063393233636164323034303166326534656665653832353261323332646438
  6661303762343061340a616264323930633630663737646439353062333963393535663261363431
  34643938653732343161323834363666613432363331663139626639313330353262

__nodepool_clouds_yaml_limestone_project_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34626666386534646136363064396235316232353864373937336562323137653235313631353530
  3462613563376534663733373866623039623038616439610a333632343066646466353133643536
  30646166373232663130666538313561643536343934636333326237383064336137653333313266
  3266633562373661660a316632333239646135376264643836643030396564306661666437313136
  31306262303532643737313265663134363933336533383934356561616538653964666530646637
  3065393961376632663064343231623939373134656663313865

__nodepool_clouds_yaml_limestone_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38313836666462656263303034363335386161383437656238666366383364653439346135643236
  3835383535353330373630613665396662613831616633640a383531666466656362346132326530
  30616661323834653565633236646162656238336638626563666336366232336530643433313465
  3531366336363863360a363963303765643732343335346430663865393963306263323963623135
  3531

__nodepool_clouds_yaml_vexxhost_ansible_network_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66333035666437396436383431303663303035663462313231666330363739373131363534353263
  3838333730616535636331373630613730353561313166610a663237323866376130623432653632
  30306361653963646662356361656634643536663039313364323939363433646363343030663963
  6332396435326165350a346135386235613832336339343466383636666635623232336264393735
  38306163383837383031643935363233626336653037396364636663663738343933396532366132
  6338393563666430316261333739323666343538303133643235

__nodepool_clouds_yaml_vexxhost_ansible_network_project_name: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33303332363233323838303630373265613734643032306537306461643165626338393331656531
  3234343462366561326139346664393761363961303066630a386364393230643435336131316664
  36343438393666356531343535646265353138666664376631386532666534653663326666346434
  3839336536633035340a633136303332343838343338376234313937656361386238306535646266
  66656264623739616563353639313236373564333939303464333438373938626638

__nodepool_clouds_yaml_vexxhost_ansible_network_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65653266396637636332333462623965653732636564663032646463643730383638383833316536
  3730346463356365323332623338376361383538353233340a643263663663356232386238666330
  37656365316166656434356662303465336464663834313561336436646562323066326535396563
  3635316463303438620a666134356637363338366664653363396562346136616661653162613830
  3138
