# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
# TODO(pabelanger): Until we rebuild borg01 and bastion01, just add dmellado
# to nodepool group
_windmill_root_users_extra:
  - dmellado

# windmill.nodepool
nodepool_user_shell: /bin/bash

nodepool_file_builder_logging_conf_manage: false
nodepool_file_launcher_logging_conf_manage: false

nodepool_file_nodepool_builder_service_config_manage: false
nodepool_file_nodepool_builder_service_manage: false

nodepool_file_nodepool_launcher_service_config_manage: false
nodepool_file_nodepool_launcher_service_manage: false

nodepool_file_nodepool_yaml_src: "{{ windmill_config_git_dest }}/nodepool/nodepool.yaml"
nodepool_file_secure_conf_src: "{{ windmill_config_git_dest }}/nodepool/secure.conf.j2"

nodepool_service_nodepool_builder_enabled: false
nodepool_service_nodepool_builder_manage: false
nodepool_service_nodepool_builder_state: stopped

nodepool_service_nodepool_launcher_enabled: false
nodepool_service_nodepool_launcher_manage: false
nodepool_service_nodepool_launcher_state: stopped

nodepool_pip_version: 3.8.0
nodepool_pip_virtualenv_python: python3
nodepool_pip_virtualenv: "/opt/venv/nodepool-{{ nodepool_pip_version }}"

# windmill.openstacksdk
openstacksdk_user_name: nodepool
openstacksdk_user_group: nodepool
openstacksdk_user_home: /var/lib/nodepool

openstacksdk_pip_virtualenv_python: python3
openstacksdk_pip_virtualenv: "{{ nodepool_pip_virtualenv }}"

openstacksdk_file_clouds_yaml_src: "{{ windmill_config_git_dest }}/nodepool/clouds.yaml.j2"

# clouds.yaml
__nodepool_clouds_yaml_limestone_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36393737616662373736343639336364313137323337383664666432656161653439363161313766
  6139323831366432616165653863383461333336366231370a393464383364663537303430363438
  66346232346666353063393233636164323034303166326534656665653832353261323332646438
  6661303762343061340a616264323930633630663737646439353062333963393535663261363431
  34643938653732343161323834363666613432363331663139626639313330353262

__nodepool_clouds_yaml_limestone_project_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34626666386534646136363064396235316232353864373937336562323137653235313631353530
  3462613563376534663733373866623039623038616439610a333632343066646466353133643536
  30646166373232663130666538313561643536343934636333326237383064336137653333313266
  3266633562373661660a316632333239646135376264643836643030396564306661666437313136
  31306262303532643737313265663134363933336533383934356561616538653964666530646637
  3065393961376632663064343231623939373134656663313865

__nodepool_clouds_yaml_limestone_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38313836666462656263303034363335386161383437656238666366383364653439346135643236
  3835383535353330373630613665396662613831616633640a383531666466656362346132326530
  30616661323834653565633236646162656238336638626563666336366232336530643433313465
  3531366336363863360a363963303765643732343335346430663865393963306263323963623135
  3531

__nodepool_clouds_yaml_ovh_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36313462373833613962316166383439646238633734393138636365373834376634616161376539
  6361353333626638343565613165343461313332616632370a356439343534343434333438376461
  66623165396231306565663063336531656564636133326337343834323062623165373131356239
  3130323931623463380a376166346235636638313730656666623534393762616666373532376465
  62643434653637313864383965316263333632386630356232626366616663366536373331636331
  3237636564353162666234363834356161656330643566386432

__nodepool_clouds_yaml_ovh_project_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32323938666564376465353831303166313435306335316264323036633037313334336562653361
  3934393863313938623166653030343662336331646633390a346238363536666638616536633264
  66363066663036383137643566336564306435363831343563386665363135353037666135643034
  6134363139666235620a383663363932313637323735626130653830623631616434303363326234
  34653533306266616135666666623330353063653438633030633730356630386633623466633638
  6334346233653762333266393162363662343066343538366665

__nodepool_clouds_yaml_ovh_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66313337636232326262636362363439626366633962306363333131376238303030623464396366
  3538366261306332623531666435363365663032343666610a363366326565646537373835623535
  64366639366530613739643033366338313932306466396532656665666161306438306264386363
  6432346437303130310a646636316164623135393638623763666538613638306236663362626235
  6332

__nodepool_clouds_yaml_vexxhost_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36303132623630343065396535306563373763643838336232343135366462663332313836616163
  3037303066656263613564616639313963306430336239320a366462336238383166383433633332
  31323766393439303065303163383261626439316566623464306638623562333664383866653165
  6364616336623839310a633261313539393738303632333761323463643931326233656266653338
  62343031316436623239326339346139323065316534356430636662623063666334353963653766
  6463623835666263623939663962623033663530373030353466

__nodepool_clouds_yaml_vexxhost_project_name: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64643335343833616235366466343331343937316439383439666462653932653032386438336630
  6164326333363839303833326562626432333136653961370a306435376665646536303738386363
  31643465373336363131363834663735626666333130623230353162636162356266623661353362
  3562316366383132300a386464646635373439386439643661353039376665346137316239316539
  39613166613561663664306561346535333237373764623264626232323938653065386136653364
  6431663563313737376633313831333334613362316565393132

__nodepool_clouds_yaml_vexxhost_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62646131316563613262326461636662313561626565333462373163303761303835383633623533
  3832363836323637366235663166616262373066373232350a663761663239376666663064646631
  63633239323366633831316434373934396539363933366531643734656361366639376466623130
  3435316663316538620a333330313936396166396634623037663638396164353664303436636132
  65653232353631376437303135316631333834396534626466306562313465663632623138626638
  3836323639393735313530326437336262353632366462326437
