---
all:
  hosts:
    bastion01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.150
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIJwUngYI3KGYjZ3kFlX11bo3OS/ZS92wKQGEnIoQjxgS
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.150
        public_ipv6: ''

    borg01.ca-ymq-1.vexxhost.zuul.ansible.com:
      ansible_host: 199.204.45.30
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIAFZWe0wD8u5CdNUOwhs9y2v4HySn808mu/oZtlF1+6O
      ansible_user: windmill
      node_attributes:
        public_ipv4: 199.204.45.30
        public_ipv6: 2604:e100:1:0:f816:3eff:feb5:6f21

    db01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.31
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIFyTdv2yZts1+Cex2h6js9gISFet0gfHX0Y4iJf21mpZ
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.31
        public_ipv6: ''

    nb01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.140
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAINcr0VzVHKiwur5AsyhwmrcghNYKL5Hu6/4CslP5hhwA
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.140
        public_ipv6: ''

    nb02.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.142
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIHsmntd2i7awAqHtKp/qyw4MMbpfeFJmjFpo8/Jy6vBe
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.142
        public_ipv6: ''

    nl01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.97
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIDdZD09g/WC7nzkeaZEbJvz9RvvkwR5wvcQzImd7ytFl
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.97
        public_ipv6: ''

    nl02.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.81
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIPQoRolVpe+abNzPIBMvN1V6iET9giP/b9FQ++v/3YAs
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.81
        public_ipv6: ''

    statsd01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.137
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIIVaj6gc20eZ0BKMa8OxGIVgbnOAYlBEbZq1zybaPMVY
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.137
        public_ipv6: ''

    zk01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.117
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIPUWGpeKtaBs2i8V/p9bbAGqik2ii1m/81tRozOxXYpY
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.117
        public_ipv6: ''

    zk02.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.104
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIEgn4v5imxlcVEkpg55BwP184hmJvaSj3Psm4AL5yvUa
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.104
        public_ipv6: ''

    zk03.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.107
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAINzwVIE4orZs2qMbkowflFq2sD/221kmdZFS7Lw/9Ws7
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.107
        public_ipv6: ''

    ze01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.100
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIIH3ZD+AwxQUaGiZj7vGw7tH/JoZNVWZDkxuWd/nG/at
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.100
        public_ipv6: ''

    ze02.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.109
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIIpw7AQlQdLTGTfjYxbEF0ylbgaDOFEaQ8MgxXCjCimK
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.109
        public_ipv6: ''

    zm01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.49
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAINeofBzQGRkZrmRxHLF62VlAgFsEAX/g81toILZVocZE
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.49
        public_ipv6: ''

    zm02.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.159
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIFfZtSxXmk41qIEms8oum6Hnz2NTiO32+3GlaJVnJ0iy
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.159
        public_ipv6: ''

    zs01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.139
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIODmTUqCV99yT9K/7yF9v7aIWtAO6mcn8WtqCP2TguZd
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.139
        public_ipv6: ''

    zw01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.96
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIE6/CA7/o763GUDYoQVSDqIrR2X7NoH6W5r/vRRC116U
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.96
        public_ipv6: ''

  children:
    bastion:
      hosts:
        bastion01.sjc1.vexxhost.zuul.ansible.com:

    borg:
      children:
        borg-client: {}
        borg-server: {}

    # NOTE(pabelanger): Remember to create borgmatic configuration and
    # encryption_passphrase each time we add a new host to borg-client
    # group.
    borg-client:
      children:
        bastion: {}
        zookeeper: {}
        zuul-scheduler: {}

    borg-server:
      hosts:
        borg01.ca-ymq-1.vexxhost.zuul.ansible.com:

    # NOTE(pabelanger): We currently only support a single database host in
    # this group.  This means, the first host listed will only be used by our
    # configuration.
    #
    # The host in this group was manually provisioned, this means if we lose
    # this host for any reason, we need to rebuild it by hand. ASAP create
    # ansible playbooks / roles to properly automate this into a fully HA
    # deployment.
    database:
      hosts:
        db01.sjc1.vexxhost.zuul.ansible.com:

    # NOTE(pabelanger): Hosts added to the disabled group will not have
    # playbooks run against them.
    disabled: {}

    # NOTE(pabelanger): We currently only support a single gear host in this
    # group.  This means, the first host listed will only be used by our
    # configuration.
    gear:
      hosts:
        zs01.sjc1.vexxhost.zuul.ansible.com:

    nodepool:
      children:
        nodepool-builder: {}
        nodepool-launcher: {}

    nodepool-builder:
      hosts:
        nb01.sjc1.vexxhost.zuul.ansible.com:
        nb02.sjc1.vexxhost.zuul.ansible.com:

    nodepool-launcher:
      hosts:
        nl01.sjc1.vexxhost.zuul.ansible.com:
        nl02.sjc1.vexxhost.zuul.ansible.com:

    # NOTE(pabelanger): We currently only support a single statsd host in this
    # group.  This means, the first host listed will only be used by our
    # configuration.
    statsd:
      hosts:
        statsd01.sjc1.vexxhost.zuul.ansible.com:

    zookeeper:
      hosts:
        zk01.sjc1.vexxhost.zuul.ansible.com:
        zk02.sjc1.vexxhost.zuul.ansible.com:
        zk03.sjc1.vexxhost.zuul.ansible.com:

    zuul:
      children:
        zuul-executor: {}
        zuul-fingergw: {}
        zuul-merger: {}
        zuul-scheduler: {}
        zuul-web: {}

    zuul-connections:
      children:
        zuul-executor: {}
        zuul-merger: {}
        zuul-scheduler: {}

    zuul-executor:
      hosts:
        ze01.sjc1.vexxhost.zuul.ansible.com:
        ze02.sjc1.vexxhost.zuul.ansible.com:

    # NOTE(pabelanger): We currently only support a single zuul-fingergw host
    # in this group.  This means, the first host listed will only be used by
    # our configuration.
    zuul-fingergw: {}

    zuul-merger:
      hosts:
        zm01.sjc1.vexxhost.zuul.ansible.com:
        zm02.sjc1.vexxhost.zuul.ansible.com:

    zuul-scheduler:
      hosts:
        zs01.sjc1.vexxhost.zuul.ansible.com:

    zuul-web:
      hosts:
        zw01.sjc1.vexxhost.zuul.ansible.com:
